apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\mkont\PycharmProjects\RiskML\kompose.exe convert
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: minio
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\mkont\PycharmProjects\RiskML\kompose.exe convert
        kompose.version: 1.25.0 (a70f80cc)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: minio
    spec:
      containers:
        - args:
            - server
            - /mlflow_bucket
          env:
            - name: MINIO_ACCESS_KEY
              value: minio-id
            - name: MINIO_SECRET_KEY
              value: minio-key
          image: minio/minio:RELEASE.2020-12-18T03-27-42Z
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:9000/minio/health/live
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 10
          name: myminio
          ports:
            - containerPort: 9000
          resources: {}
          volumeMounts:
            - mountPath: /mlflow_bucket
              name: artifact-store
      restartPolicy: Always
      volumes:
        - name: artifact-store
          persistentVolumeClaim:
            claimName: artifact-store
status: {}
