apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\mkont\PycharmProjects\RiskML\Deployment\kompose.exe convert
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: create-bucket
  name: create-bucket
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: create-bucket
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\mkont\PycharmProjects\RiskML\Deployment\kompose.exe convert
        kompose.version: 1.25.0 (a70f80cc)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: create-bucket
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - ' /usr/bin/mc config host rm local; /usr/bin/mc config host add --quiet --api s3v4 local http://myminio:9000 minio-id minio-key; /usr/bin/mc rb --force local/mlflow-bucket/; /usr/bin/mc mb --quiet local/mlflow-bucket/; /usr/bin/mc policy set public local/mlflow-bucket; '
          env:
            - name: MINIO_ACCESS_KEY
              value: minio-id
            - name: MINIO_SECRET_KEY
              value: minio-key
            - name: PORT
              value: "9000"
          image: minio/mc:RELEASE.2019-07-17T22-13-42Z
          name: create-bucket
          resources: {}
      restartPolicy: Always
status: {}
