apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\mkont\PycharmProjects\RiskML\Deployment\kompose.exe convert
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: mlflow-server
  name: mlflow-server
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
    - name: 5000-tcp
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: mlflow-server
status:
  loadBalancer: {}
