apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\mkont\PycharmProjects\RiskML\Deployment\kompose.exe convert
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: pgdb
  name: pgdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pgdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\mkont\PycharmProjects\RiskML\Deployment\kompose.exe convert
        kompose.version: 1.25.0 (a70f80cc)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: pgdb
    spec:
      containers:
        - env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DATABASE
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_USER
          image: pgdb
          name: pgdb
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: database
      restartPolicy: Always
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: database
status: {}
