apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\mkont\PycharmProjects\RiskML\Deployment\kompose.exe convert
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: pgdb
  name: pgdb
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
    - name: 5432-tcp
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: pgdb
status:
  loadBalancer: {}
